[package]
name = "inject"
version = "0.1.0"
edition = "2021"

[lib]
name = "inject"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
ctor = "0.2.5"
goblin = "0.7.1"
nix = { version = "0.27.1", features = ["socket"] }
once_cell = "1.19.0"
url = "2.5.0"
