#!/usr/bin/env python3
import os
import sys
from sys import argv
from urllib import parse


def my_exec(*args):
    env = set(os.environ['PATH'].split(':'))
    env.remove('/opt/QQ/__patch__')
    os.environ['PATH'] = ':'.join(env)
    os.execvp('xdg-open', ['xdg-open', *args])
    exit(1)


if len(argv) == 1:
    my_exec(*argv[1:])

result = parse.urlsplit(argv[1])

if result.netloc == 'c.pc.qq.com':
    my_exec(parse.parse_qs(result.query)['pfurl'][0])

my_exec(*argv[1:])
