name: Build CI

on:
  push:
    branches: [ archlinux ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Arch
        uses: docker://archlinux:latest
        with:
          entrypoint: /bin/bash
          args: .github/workflows/scripts/ci.sh

      - name: Prepare Artifact
        id: prepare_artifact
        run: |
          echo "name=$(echo qwrapper*.pkg* | sed 's/.pkg.*//')" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepare_artifact.outputs.name }}
          path: |
            PKGBUILD
            qwrapper*.pkg.*
